import { getSession } from "@/server/better-auth/server";
import { redirect } from "next/navigation";
import type { ReactNode } from "react";

export const metadata = {
  title: "TalentLens | Auth",
  description: "Generated by Love ❤️",
};

export default async function AuthLayout({
  children,
}: {
  children: ReactNode;
}) {
  const sessionData = await getSession();

  if (sessionData?.session) {
    redirect("/dashboard");
  }

  return <>{children}</>;
}