import { getSession } from "@/server/better-auth/server";
import { redirect } from "next/navigation";
import type { ReactNode } from "react";

export const metadata = {
    title: "TalentLens | Dashboard",
    description: "Generated by Love ❤️",
};

export default async function ProtectedLayout({ children } : { children: ReactNode}){
    const sessionData = await getSession();
    
      if (!sessionData?.session) {
        redirect("/login");
      }
      
    return (
        <>
            {children}
        </>
    )
}